# Generated by Django 2.2.4 on 2022-09-15 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='user',
        ),
    ]
