version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t routing . 
      - docker tag routing:latest 985290329026.dkr.ecr.us-east-1.amazonaws.com/django
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 985290329026.dkr.ecr.us-east-1.amazonaws.com/django
